---
title: "Resume Experiment"
format: html
execute: 
    echo: false
---




```{r}
#| message: false
#| warning: false
library(tidyverse)
library(tidymodels)
library(broom)
library(marginaleffects)
library(easystats)
library(caret)      # For model training and evaluation
library(broom)      # For tidy model output
x <- read_csv("https://raw.githubusercontent.com/PPBDS/bootcamp/refs/heads/master/_internal/data/resume.csv",
        show_col_types = FALSE)

```


<!-- name indicates applicant's first name.

gender indicates gender.

ethnicity indicates ethnicity (i.e., Caucasian-sounding vs. African-American sounding first name).

quality indicatesquality of resume.

call indicates whether the applicant was called back?

city indicates city: Boston or Chicago.

jobs indicates number of jobs listed on resume.

experience indicates number of years of work experience on the resume.

honors: Did the resume mention some honors?

holes: Does the resume have some employment holes?

special: Does the resume mention some special skills? -->


```{r}
# Load libraries
#| warning: false
#| message: false
library(tidyverse)
library(tidymodels)
library(pROC)
```


# Preprocess data
```{r}
logistic_reg() |> 
  fit(as.factor(call) ~ city + ethnicity + gender + experience + holes , data = x) |> 
  tidy(conf.int = TRUE)



# the tidy(conf.int = TRUE) takes out the call & coeffi
# neg coefficent for the intercept means that there will be less liklihood of getting a callback 
# compared to the reference city, & in this case the ref city is Boston, so Chicago has a less likelihood
# of getting a callback compared to bostom

# the fact that the conf interval excludes zero tells us that we are 95% sure that being in chicago 
# decreases our chances of getting a callback 
# if conf interval (conf.low - conf.high has zero) included zero = we aren't confident, possible results due to chance 
# 95% CI: [8.4, ] ~ tells us the upper and lower bounds
```



